# Generated by Django 5.1.6 on 2025-05-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='birthdate',
            new_name='date',
        ),
        migrations.AddField(
            model_name='record',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='srp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='total_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
