# Generated by Django 5.1.6 on 2025-05-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0002_rename_birthdate_record_date_record_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
