# Generated by Django 5.1.6 on 2025-05-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0003_record_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
