# Generated by Django 5.1.6 on 2025-05-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0004_alter_record_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='price',
        ),
    ]
