# Generated by Django 5.1.6 on 2025-05-31 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk', '0006_remove_record_profit_record_total_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='srp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
